export const IMAGES = {
  splashBg: require('../assets/images/imgbg.png'),
  logo: require('../assets/images/logo.png'),
  cards: require('../assets/images/card.png'),
  CARDBLACK: require('../assets/images/cardback.png'),
  cardBrown: require('../assets/images/cardfront.png'),
  handCard: require('../assets/images/Handcard.png'),
  otpIllustration: require('../assets/images/OTP 1.png'),
  faceGlow: require('../assets/images/Group 4.png'),
  faceIcon: require('../assets/images/Face ID Symbol.png'),
  blackCardTilted: require('../assets/images/Vector 19.png'),
  crownCardTilted: require('../assets/images/Group 6.png'),
  chipIcon: require('../assets/images/Chip.png'),
  RepeatIcon: require('../assets/images/repeat.png'),
  StarBucksLogo: require('../assets/images/Starbucks.png'),
  AmazonLogo: require('../assets/images/amazon.png'),
  DominozLogo: require('../assets/images/Pizza.png'),
  NikeLogo: require('../assets/images/Nike.png'),
  CheckIcon: require('../assets/images/check-circle.png'),
  
};